--delete from departamento;
--delete from localidad;
--truncate table localidad cascade;
--select * from departamento;
--delete from departamento;
--truncate table departamento;

/*-- DEPARTAMENTOS --*/

insert into departamento (nombre) values ('CANELONES');
insert into departamento (nombre) values ('MALDONADO');
insert into departamento (nombre) values ('ROCHA');
insert into departamento (nombre) values ('TREINTA Y TRES');
insert into departamento (nombre) values ('CERRO LARGO');
insert into departamento (nombre) values ('RIVERA');
insert into departamento (nombre) values ('ARTIGAS');
insert into departamento (nombre) values ('SALTO');
insert into departamento (nombre) values ('PAYSANDU');
insert into departamento (nombre) values ('RIO NEGRO');
insert into departamento (nombre) values ('SORIANO');
insert into departamento (nombre) values ('COLONIA');
insert into departamento (nombre) values ('SAN JOSE');
insert into departamento (nombre) values ('FLORES');
insert into departamento (nombre) values ('FLORIDA');
insert into departamento (nombre) values ('LAVALLEJA');
insert into departamento (nombre) values ('DURAZNO');
insert into departamento (nombre) values ('TACUAREMBO');
insert into departamento (nombre) values ('MONTEVIDEO');



-- CANELONES
insert into localidad (nombre, id_dep) select 'CANELONES', d.id_dep from departamento d where d.nombre = 'CANELONES';
insert into localidad (nombre, id_dep) select 'JOANICO', d.id_dep from departamento d where d.nombre = 'CANELONES';
insert into localidad (nombre, id_dep) select 'SANTA LUCIA', d.id_dep from departamento d where d.nombre = 'CANELONES';
insert into localidad (nombre, id_dep) select 'EMPALME', d.id_dep from departamento d where d.nombre = 'CANELONES';
insert into localidad (nombre, id_dep) select 'CERRILLOS', d.id_dep from departamento d where d.nombre = 'CANELONES';
insert into localidad (nombre, id_dep) select 'AGUAS CORRIENTES', d.id_dep from departamento d where d.nombre = 'CANELONES';
insert into localidad (nombre, id_dep) select 'LAS PIEDRAS', d.id_dep from departamento d where d.nombre = 'CANELONES';
insert into localidad (nombre, id_dep) select 'LA PAZ', d.id_dep from departamento d where d.nombre = 'CANELONES';
insert into localidad (nombre, id_dep) select 'MARIO FERREIRA', d.id_dep from departamento d where d.nombre = 'CANELONES';
insert into localidad (nombre, id_dep) select 'SOFIA SANTOS', d.id_dep from departamento d where d.nombre = 'CANELONES';
insert into localidad (nombre, id_dep) select 'SAUCE', d.id_dep from departamento d where d.nombre = 'CANELONES';
insert into localidad (nombre, id_dep) select 'TOLEDO CHICO', d.id_dep from departamento d where d.nombre = 'CANELONES';
insert into localidad (nombre, id_dep) select 'SAN RAMON', d.id_dep from departamento d where d.nombre = 'CANELONES';
insert into localidad (nombre, id_dep) select 'SAN BAUTISTA', d.id_dep from departamento d where d.nombre = 'CANELONES';
insert into localidad (nombre, id_dep) select 'EST.CASTELLANO', d.id_dep from departamento d where d.nombre = 'CANELONES';
insert into localidad (nombre, id_dep) select 'SANTA ROSA', d.id_dep from departamento d where d.nombre = 'CANELONES';
insert into localidad (nombre, id_dep) select 'SAN ANTONIO', d.id_dep from departamento d where d.nombre = 'CANELONES';
insert into localidad (nombre, id_dep) select 'PROGRESO', d.id_dep from departamento d where d.nombre = 'CANELONES';
insert into localidad (nombre, id_dep) select 'CANELON CHICO', d.id_dep from departamento d where d.nombre = 'CANELONES';
insert into localidad (nombre, id_dep) select 'EST. FLORESTA', d.id_dep from departamento d where d.nombre = 'CANELONES';
insert into localidad (nombre, id_dep) select 'PANDO', d.id_dep from departamento d where d.nombre = 'CANELONES';
insert into localidad (nombre, id_dep) select 'PBLO ARTIGAS', d.id_dep from departamento d where d.nombre = 'CANELONES';
insert into localidad (nombre, id_dep) select 'EMPALME OLMOS', d.id_dep from departamento d where d.nombre = 'CANELONES';
insert into localidad (nombre, id_dep) select 'ESTACION OLMOS', d.id_dep from departamento d where d.nombre = 'CANELONES';
insert into localidad (nombre, id_dep) select 'P. DEL TORO', d.id_dep from departamento d where d.nombre = 'CANELONES';
insert into localidad (nombre, id_dep) select 'TOTORAL SAUCE', d.id_dep from departamento d where d.nombre = 'CANELONES';
insert into localidad (nombre, id_dep) select 'NEPTUNIA', d.id_dep from departamento d where d.nombre = 'CANELONES';
insert into localidad (nombre, id_dep) select 'PINAMAR', d.id_dep from departamento d where d.nombre = 'CANELONES';
insert into localidad (nombre, id_dep) select 'PINE PARK', d.id_dep from departamento d where d.nombre = 'CANELONES';
insert into localidad (nombre, id_dep) select 'SALINAS', d.id_dep from departamento d where d.nombre = 'CANELONES';
insert into localidad (nombre, id_dep) select 'ATLANTIDA', d.id_dep from departamento d where d.nombre = 'CANELONES';
insert into localidad (nombre, id_dep) select 'PQUE DEL PLATA', d.id_dep from departamento d where d.nombre = 'CANELONES';
insert into localidad (nombre, id_dep) select 'COLONIA NICOLICH', d.id_dep from departamento d where d.nombre = 'CANELONES';
insert into localidad (nombre, id_dep) select 'LA MONTAÑESA', d.id_dep from departamento d where d.nombre = 'CANELONES';
insert into localidad (nombre, id_dep) select 'EST.ATLANTIDA', d.id_dep from departamento d where d.nombre = 'CANELONES';
insert into localidad (nombre, id_dep) select 'EST.P.AFILAR', d.id_dep from departamento d where d.nombre = 'CANELONES';
insert into localidad (nombre, id_dep) select 'MARINDIA', d.id_dep from departamento d where d.nombre = 'CANELONES';
insert into localidad (nombre, id_dep) select 'FORTIN S.ROSA', d.id_dep from departamento d where d.nombre = 'CANELONES';
insert into localidad (nombre, id_dep) select 'LAS TOSCAS', d.id_dep from departamento d where d.nombre = 'CANELONES';
insert into localidad (nombre, id_dep) select 'SOCA', d.id_dep from departamento d where d.nombre = 'CANELONES';
insert into localidad (nombre, id_dep) select 'MIGUES', d.id_dep from departamento d where d.nombre = 'CANELONES';
insert into localidad (nombre, id_dep) select 'MONTES', d.id_dep from departamento d where d.nombre = 'CANELONES';
insert into localidad (nombre, id_dep) select 'CAPILLA CELLA', d.id_dep from departamento d where d.nombre = 'CANELONES';
insert into localidad (nombre, id_dep) select 'ESTACION MIGUES', d.id_dep from departamento d where d.nombre = 'CANELONES';
insert into localidad (nombre, id_dep) select 'ESTACION MONTE', d.id_dep from departamento d where d.nombre = 'CANELONES';
insert into localidad (nombre, id_dep) select 'LA TUNA', d.id_dep from departamento d where d.nombre = 'CANELONES';
insert into localidad (nombre, id_dep) select 'LOS TITANES', d.id_dep from departamento d where d.nombre = 'CANELONES';
insert into localidad (nombre, id_dep) select 'STA.LUCIA ESTE', d.id_dep from departamento d where d.nombre = 'CANELONES';
insert into localidad (nombre, id_dep) select 'ARAMINDA', d.id_dep from departamento d where d.nombre = 'CANELONES';
insert into localidad (nombre, id_dep) select 'BIARRITZ', d.id_dep from departamento d where d.nombre = 'CANELONES';
insert into localidad (nombre, id_dep) select 'CUCHILLA ALTA', d.id_dep from departamento d where d.nombre = 'CANELONES';
insert into localidad (nombre, id_dep) select 'SANTA ANA', d.id_dep from departamento d where d.nombre = 'CANELONES';
insert into localidad (nombre, id_dep) select 'TALA', d.id_dep from departamento d where d.nombre = 'CANELONES';
insert into localidad (nombre, id_dep) select 'SAN JACINTO', d.id_dep from departamento d where d.nombre = 'CANELONES';
insert into localidad (nombre, id_dep) select 'RUTA 7 KM 45', d.id_dep from departamento d where d.nombre = 'CANELONES';
insert into localidad (nombre, id_dep) select 'JQUIN.SUAREZ', d.id_dep from departamento d where d.nombre = 'CANELONES';
insert into localidad (nombre, id_dep) select 'LA FLORESTA', d.id_dep from departamento d where d.nombre = 'CANELONES';
insert into localidad (nombre, id_dep) select 'BOLIVAR', d.id_dep from departamento d where d.nombre = 'CANELONES';
insert into localidad (nombre, id_dep) select 'ESTACION TAPIA', d.id_dep from departamento d where d.nombre = 'CANELONES';
insert into localidad (nombre, id_dep) select 'PEDRERA', d.id_dep from departamento d where d.nombre = 'CANELONES';
insert into localidad (nombre, id_dep) select 'JAUREGUIBERRY', d.id_dep from departamento d where d.nombre = 'CANELONES';
insert into localidad (nombre, id_dep) select 'SAN LUIS', d.id_dep from departamento d where d.nombre = 'CANELONES';
insert into localidad (nombre, id_dep) select 'COSTA AZUL', d.id_dep from departamento d where d.nombre = 'CANELONES';
insert into localidad (nombre, id_dep) select 'B.HORIZONTE', d.id_dep from departamento d where d.nombre = 'CANELONES';
insert into localidad (nombre, id_dep) select 'GUAZUVIRA', d.id_dep from departamento d where d.nombre = 'CANELONES';
insert into localidad (nombre, id_dep) select 'TOLEDO', d.id_dep from departamento d where d.nombre = 'CANELONES';
insert into localidad (nombre, id_dep) select 'BAL.ARGENTINO', d.id_dep from departamento d where d.nombre = 'CANELONES';
insert into localidad (nombre, id_dep) select 'C. DE LA COSTA', d.id_dep from departamento d where d.nombre = 'CANELONES';
insert into localidad (nombre, id_dep) select 'RODO', d.id_dep from departamento d where d.nombre = 'CANELONES';
insert into localidad (nombre, id_dep) select 'Sin Localidad', d.id_dep from departamento d where d.nombre = 'CANELONES';

-- MALDONADO
insert into localidad (nombre, id_dep) select 'MALDONADO', d.id_dep from departamento d where d.nombre = 'MALDONADO';
insert into localidad (nombre, id_dep) select 'BRIO.MALDONADO', d.id_dep from departamento d where d.nombre = 'MALDONADO';
insert into localidad (nombre, id_dep) select 'PUNTA DEL ESTE', d.id_dep from departamento d where d.nombre = 'MALDONADO';
insert into localidad (nombre, id_dep) select 'PUNTA BALLENA', d.id_dep from departamento d where d.nombre = 'MALDONADO';
insert into localidad (nombre, id_dep) select 'SAN CARLOS', d.id_dep from departamento d where d.nombre = 'MALDONADO';
insert into localidad (nombre, id_dep) select 'EL TESORO', d.id_dep from departamento d where d.nombre = 'MALDONADO';
insert into localidad (nombre, id_dep) select 'LA BARRA', d.id_dep from departamento d where d.nombre = 'MALDONADO';
insert into localidad (nombre, id_dep) select 'MANANTIALES', d.id_dep from departamento d where d.nombre = 'MALDONADO';
insert into localidad (nombre, id_dep) select 'EL CHORRO', d.id_dep from departamento d where d.nombre = 'MALDONADO';
insert into localidad (nombre, id_dep) select 'BUENOS AIRES', d.id_dep from departamento d where d.nombre = 'MALDONADO';
insert into localidad (nombre, id_dep) select 'SAN VICENTE', d.id_dep from departamento d where d.nombre = 'MALDONADO';
insert into localidad (nombre, id_dep) select 'EDEN ROCK', d.id_dep from departamento d where d.nombre = 'MALDONADO';
insert into localidad (nombre, id_dep) select 'SANTA MONICA', d.id_dep from departamento d where d.nombre = 'MALDONADO';
insert into localidad (nombre, id_dep) select 'LA JUANITA', d.id_dep from departamento d where d.nombre = 'MALDONADO';
insert into localidad (nombre, id_dep) select 'FARO J.IGNACIO', d.id_dep from departamento d where d.nombre = 'MALDONADO';
insert into localidad (nombre, id_dep) select 'AIGUA', d.id_dep from departamento d where d.nombre = 'MALDONADO';
insert into localidad (nombre, id_dep) select 'GARZON', d.id_dep from departamento d where d.nombre = 'MALDONADO';
insert into localidad (nombre, id_dep) select 'HIPODROMO', d.id_dep from departamento d where d.nombre = 'MALDONADO';
insert into localidad (nombre, id_dep) select 'EL EDEN', d.id_dep from departamento d where d.nombre = 'MALDONADO';
insert into localidad (nombre, id_dep) select 'PIRIAPOLIS', d.id_dep from departamento d where d.nombre = 'MALDONADO';
insert into localidad (nombre, id_dep) select 'PAN DE AZUCAR', d.id_dep from departamento d where d.nombre = 'MALDONADO';
insert into localidad (nombre, id_dep) select 'CERROS AZULES', d.id_dep from departamento d where d.nombre = 'MALDONADO';
insert into localidad (nombre, id_dep) select 'KILOMETRO 110', d.id_dep from departamento d where d.nombre = 'MALDONADO';
insert into localidad (nombre, id_dep) select 'LA CAPUERA', d.id_dep from departamento d where d.nombre = 'MALDONADO';
insert into localidad (nombre, id_dep) select 'SIERRAS TIROL', d.id_dep from departamento d where d.nombre = 'MALDONADO';
insert into localidad (nombre, id_dep) select 'VENTIMIGLIA', d.id_dep from departamento d where d.nombre = 'MALDONADO';
insert into localidad (nombre, id_dep) select 'OCEAN PARK', d.id_dep from departamento d where d.nombre = 'MALDONADO';
insert into localidad (nombre, id_dep) select 'SCE.PORTEZUELO', d.id_dep from departamento d where d.nombre = 'MALDONADO';
insert into localidad (nombre, id_dep) select 'BAR PORTEZUELO', d.id_dep from departamento d where d.nombre = 'MALDONADO';
insert into localidad (nombre, id_dep) select 'PUNTA NEGRA', d.id_dep from departamento d where d.nombre = 'MALDONADO';
insert into localidad (nombre, id_dep) select 'PUNTA COLORADA', d.id_dep from departamento d where d.nombre = 'MALDONADO';
insert into localidad (nombre, id_dep) select 'BALN.SOLIS', d.id_dep from departamento d where d.nombre = 'MALDONADO';
insert into localidad (nombre, id_dep) select 'GRIO.AZNAREZ', d.id_dep from departamento d where d.nombre = 'MALDONADO';
insert into localidad (nombre, id_dep) select 'EST. SOLIS', d.id_dep from departamento d where d.nombre = 'MALDONADO';
insert into localidad (nombre, id_dep) select 'KILOMETRO 84', d.id_dep from departamento d where d.nombre = 'MALDONADO';
insert into localidad (nombre, id_dep) select 'NVA.CARRARA', d.id_dep from departamento d where d.nombre = 'MALDONADO';
insert into localidad (nombre, id_dep) select 'EST.LAS FLORES', d.id_dep from departamento d where d.nombre = 'MALDONADO';
insert into localidad (nombre, id_dep) select 'BELLA VISTA', d.id_dep from departamento d where d.nombre = 'MALDONADO';
insert into localidad (nombre, id_dep) select 'LAS FLORES', d.id_dep from departamento d where d.nombre = 'MALDONADO';
insert into localidad (nombre, id_dep) select 'PLAYA VERDE', d.id_dep from departamento d where d.nombre = 'MALDONADO';
insert into localidad (nombre, id_dep) select 'PLAYA HERMOSA', d.id_dep from departamento d where d.nombre = 'MALDONADO';
insert into localidad (nombre, id_dep) select 'PLAYA GRANDE', d.id_dep from departamento d where d.nombre = 'MALDONADO';
insert into localidad (nombre, id_dep) select 'Sin Localidad', d.id_dep from departamento d where d.nombre = 'MALDONADO';

-- ROCHA
insert into localidad (nombre, id_dep) select 'ROCHA', d.id_dep from departamento d where d.nombre = 'ROCHA';
insert into localidad (nombre, id_dep) select 'CASTILLOS', d.id_dep from departamento d where d.nombre = 'ROCHA';
insert into localidad (nombre, id_dep) select 'LA PEDRERA', d.id_dep from departamento d where d.nombre = 'ROCHA';
insert into localidad (nombre, id_dep) select 'LASCANO', d.id_dep from departamento d where d.nombre = 'ROCHA';
insert into localidad (nombre, id_dep) select 'LA AGUADA', d.id_dep from departamento d where d.nombre = 'ROCHA';
insert into localidad (nombre, id_dep) select 'CHUY', d.id_dep from departamento d where d.nombre = 'ROCHA';
insert into localidad (nombre, id_dep) select 'ANTONIOPOLIS', d.id_dep from departamento d where d.nombre = 'ROCHA';
insert into localidad (nombre, id_dep) select 'VELAZQUEZ', d.id_dep from departamento d where d.nombre = 'ROCHA';
insert into localidad (nombre, id_dep) select 'ARACHANIA', d.id_dep from departamento d where d.nombre = 'ROCHA';
insert into localidad (nombre, id_dep) select 'CEBOLLATI', d.id_dep from departamento d where d.nombre = 'ROCHA';
insert into localidad (nombre, id_dep) select 'COSTA AZUL', d.id_dep from departamento d where d.nombre = 'ROCHA';
insert into localidad (nombre, id_dep) select 'ATLANTICO', d.id_dep from departamento d where d.nombre = 'ROCHA';
insert into localidad (nombre, id_dep) select '19 DE ABRIL', d.id_dep from departamento d where d.nombre = 'ROCHA';
insert into localidad (nombre, id_dep) select 'PARALLE', d.id_dep from departamento d where d.nombre = 'ROCHA';
insert into localidad (nombre, id_dep) select 'LA PALOMA', d.id_dep from departamento d where d.nombre = 'ROCHA';
insert into localidad (nombre, id_dep) select '18 DE JULIO', d.id_dep from departamento d where d.nombre = 'ROCHA';
insert into localidad (nombre, id_dep) select 'BARRA DEL CHUY', d.id_dep from departamento d where d.nombre = 'ROCHA';
insert into localidad (nombre, id_dep) select 'LA CORONILLA', d.id_dep from departamento d where d.nombre = 'ROCHA';
insert into localidad (nombre, id_dep) select 'B.LA CORONILLA', d.id_dep from departamento d where d.nombre = 'ROCHA';
insert into localidad (nombre, id_dep) select 'BARRA URUGUAYA', d.id_dep from departamento d where d.nombre = 'ROCHA';
insert into localidad (nombre, id_dep) select 'LAS GARZAS', d.id_dep from departamento d where d.nombre = 'ROCHA';
insert into localidad (nombre, id_dep) select 'PUNTA RUBIA', d.id_dep from departamento d where d.nombre = 'ROCHA';
insert into localidad (nombre, id_dep) select 'ATLANTICA', d.id_dep from departamento d where d.nombre = 'ROCHA';
insert into localidad (nombre, id_dep) select 'LA ESMERALDA', d.id_dep from departamento d where d.nombre = 'ROCHA';
insert into localidad (nombre, id_dep) select 'SANTA MARIA', d.id_dep from departamento d where d.nombre = 'ROCHA';
insert into localidad (nombre, id_dep) select 'PUIMAYEN', d.id_dep from departamento d where d.nombre = 'ROCHA';
insert into localidad (nombre, id_dep) select 'Sin Localidad', d.id_dep from departamento d where d.nombre = 'ROCHA';

-- TREINTA Y TRES
insert into localidad (nombre, id_dep) select 'TREINTA Y TRES', d.id_dep from departamento d where d.nombre = 'TREINTA Y TRES';
insert into localidad (nombre, id_dep) select 'GL.E.MARTINEZ', d.id_dep from departamento d where d.nombre = 'TREINTA Y TRES';
insert into localidad (nombre, id_dep) select 'VERGARA', d.id_dep from departamento d where d.nombre = 'TREINTA Y TRES';
insert into localidad (nombre, id_dep) select 'SANTA CLARA', d.id_dep from departamento d where d.nombre = 'TREINTA Y TRES';
insert into localidad (nombre, id_dep) select 'CERRO CHATO', d.id_dep from departamento d where d.nombre = 'TREINTA Y TRES';
insert into localidad (nombre, id_dep) select 'MARIA ISABEL', d.id_dep from departamento d where d.nombre = 'TREINTA Y TRES';
insert into localidad (nombre, id_dep) select 'MARIA ALBINA', d.id_dep from departamento d where d.nombre = 'TREINTA Y TRES';
insert into localidad (nombre, id_dep) select 'MENDIZABAL U', d.id_dep from departamento d where d.nombre = 'TREINTA Y TRES';
insert into localidad (nombre, id_dep) select 'VILLA SARA', d.id_dep from departamento d where d.nombre = 'TREINTA Y TRES';
insert into localidad (nombre, id_dep) select 'VALENTINES', d.id_dep from departamento d where d.nombre = 'TREINTA Y TRES';
insert into localidad (nombre, id_dep) select 'RINCON', d.id_dep from departamento d where d.nombre = 'TREINTA Y TRES';
insert into localidad (nombre, id_dep) select 'Sin Localidad', d.id_dep from departamento d where d.nombre = 'TREINTA Y TRES';

-- CERRO LARGO
insert into localidad (nombre, id_dep) select 'MELO', d.id_dep from departamento d where d.nombre = 'CERRO LARGO';
insert into localidad (nombre, id_dep) select 'RIO BRANCO', d.id_dep from departamento d where d.nombre = 'CERRO LARGO';
insert into localidad (nombre, id_dep) select 'FRAILE MUERTO', d.id_dep from departamento d where d.nombre = 'CERRO LARGO';
insert into localidad (nombre, id_dep) select 'DRAGON', d.id_dep from departamento d where d.nombre = 'CERRO LARGO';
insert into localidad (nombre, id_dep) select 'TUPAMBAE', d.id_dep from departamento d where d.nombre = 'CERRO LARGO';
insert into localidad (nombre, id_dep) select 'NOBLIA', d.id_dep from departamento d where d.nombre = 'CERRO LARGO';
insert into localidad (nombre, id_dep) select 'ACEGUA', d.id_dep from departamento d where d.nombre = 'CERRO LARGO';
insert into localidad (nombre, id_dep) select 'CERRO CUENTAS', d.id_dep from departamento d where d.nombre = 'CERRO LARGO';
insert into localidad (nombre, id_dep) select 'TOLEDO', d.id_dep from departamento d where d.nombre = 'CERRO LARGO';
insert into localidad (nombre, id_dep) select 'TRES ISLAS', d.id_dep from departamento d where d.nombre = 'CERRO LARGO';
insert into localidad (nombre, id_dep) select 'ESPERANZA', d.id_dep from departamento d where d.nombre = 'CERRO LARGO';
insert into localidad (nombre, id_dep) select 'BDO. DE MEDINA', d.id_dep from departamento d where d.nombre = 'CERRO LARGO';
insert into localidad (nombre, id_dep) select 'MANGRULLO', d.id_dep from departamento d where d.nombre = 'CERRO LARGO';
insert into localidad (nombre, id_dep) select 'VARGAS', d.id_dep from departamento d where d.nombre = 'CERRO LARGO';
insert into localidad (nombre, id_dep) select 'NANDO', d.id_dep from departamento d where d.nombre = 'CERRO LARGO';
insert into localidad (nombre, id_dep) select 'SOTO GORO', d.id_dep from departamento d where d.nombre = 'CERRO LARGO';
insert into localidad (nombre, id_dep) select 'LOPEZ BENITEZ', d.id_dep from departamento d where d.nombre = 'CERRO LARGO';
insert into localidad (nombre, id_dep) select 'LAGUNA MERIN', d.id_dep from departamento d where d.nombre = 'CERRO LARGO';
insert into localidad (nombre, id_dep) select 'ÑANGAPIRE', d.id_dep from departamento d where d.nombre = 'CERRO LARGO';
insert into localidad (nombre, id_dep) select 'PBDO.URUGUAY', d.id_dep from departamento d where d.nombre = 'CERRO LARGO';
insert into localidad (nombre, id_dep) select 'Sin Localidad', d.id_dep from departamento d where d.nombre = 'CERRO LARGO';

-- RIVERA
insert into localidad (nombre, id_dep) select 'RIVERA', d.id_dep from departamento d where d.nombre = 'RIVERA';
insert into localidad (nombre, id_dep) select 'TRANQUERAS', d.id_dep from departamento d where d.nombre = 'RIVERA';
insert into localidad (nombre, id_dep) select 'VICHADERO', d.id_dep from departamento d where d.nombre = 'RIVERA';
insert into localidad (nombre, id_dep) select 'LAPUENTE', d.id_dep from departamento d where d.nombre = 'RIVERA';
insert into localidad (nombre, id_dep) select 'MINAS CORRALES', d.id_dep from departamento d where d.nombre = 'RIVERA';
insert into localidad (nombre, id_dep) select 'LAG DEL NORTE', d.id_dep from departamento d where d.nombre = 'RIVERA';
insert into localidad (nombre, id_dep) select 'Sin Localidad', d.id_dep from departamento d where d.nombre = 'RIVERA';

-- ARTIGAS
insert into localidad (nombre, id_dep) select 'ARTIGAS', d.id_dep from departamento d where d.nombre = 'ARTIGAS';
insert into localidad (nombre, id_dep) select 'B.UNION', d.id_dep from departamento d where d.nombre = 'ARTIGAS';
insert into localidad (nombre, id_dep) select 'T. GOMENSORO', d.id_dep from departamento d where d.nombre = 'ARTIGAS';
insert into localidad (nombre, id_dep) select 'B.BRUM', d.id_dep from departamento d where d.nombre = 'ARTIGAS';
insert into localidad (nombre, id_dep) select 'Sin Localidad', d.id_dep from departamento d where d.nombre = 'ARTIGAS';

-- SALTO
insert into localidad (nombre, id_dep) select 'SALTO', d.id_dep from departamento d where d.nombre = 'SALTO';
insert into localidad (nombre, id_dep) select 'SALTO ARENITAS', d.id_dep from departamento d where d.nombre = 'SALTO';
insert into localidad (nombre, id_dep) select 'SALTO DAYMAN', d.id_dep from departamento d where d.nombre = 'SALTO';
insert into localidad (nombre, id_dep) select 'SALTO HUERTO', d.id_dep from departamento d where d.nombre = 'SALTO';
insert into localidad (nombre, id_dep) select 'BELEN', d.id_dep from departamento d where d.nombre = 'SALTO';
insert into localidad (nombre, id_dep) select 'CONSTITUCION', d.id_dep from departamento d where d.nombre = 'SALTO';
insert into localidad (nombre, id_dep) select 'PUEBLO ALBISU', d.id_dep from departamento d where d.nombre = 'SALTO';
insert into localidad (nombre, id_dep) select 'BIASSINI', d.id_dep from departamento d where d.nombre = 'SALTO';
insert into localidad (nombre, id_dep) select 'CELESTE', d.id_dep from departamento d where d.nombre = 'SALTO';
insert into localidad (nombre, id_dep) select 'Sin Localidad', d.id_dep from departamento d where d.nombre = 'SALTO';

-- PAYSANDU
insert into localidad (nombre, id_dep) select 'PAYSANDU', d.id_dep from departamento d where d.nombre = 'PAYSANDU';
insert into localidad (nombre, id_dep) select 'SAMARITANA', d.id_dep from departamento d where d.nombre = 'PAYSANDU';
insert into localidad (nombre, id_dep) select 'PURIFICACION', d.id_dep from departamento d where d.nombre = 'PAYSANDU';
insert into localidad (nombre, id_dep) select 'NVO  PAYSANDU', d.id_dep from departamento d where d.nombre = 'PAYSANDU';
insert into localidad (nombre, id_dep) select 'PORVENIR', d.id_dep from departamento d where d.nombre = 'PAYSANDU';
insert into localidad (nombre, id_dep) select 'PAY CHACRAS', d.id_dep from departamento d where d.nombre = 'PAYSANDU';
insert into localidad (nombre, id_dep) select 'GUICHON', d.id_dep from departamento d where d.nombre = 'PAYSANDU';
insert into localidad (nombre, id_dep) select 'QUEBRACHO', d.id_dep from departamento d where d.nombre = 'PAYSANDU';
insert into localidad (nombre, id_dep) select 'CASA BLANCA', d.id_dep from departamento d where d.nombre = 'PAYSANDU';
insert into localidad (nombre, id_dep) select 'LORENZO GEYRES', d.id_dep from departamento d where d.nombre = 'PAYSANDU';
insert into localidad (nombre, id_dep) select 'TAMBORES', d.id_dep from departamento d where d.nombre = 'PAYSANDU';
insert into localidad (nombre, id_dep) select 'PIÑERA', d.id_dep from departamento d where d.nombre = 'PAYSANDU';
insert into localidad (nombre, id_dep) select 'P. COLORADAS', d.id_dep from departamento d where d.nombre = 'PAYSANDU';
insert into localidad (nombre, id_dep) select 'MERINOS', d.id_dep from departamento d where d.nombre = 'PAYSANDU';
insert into localidad (nombre, id_dep) select 'MORATO', d.id_dep from departamento d where d.nombre = 'PAYSANDU';
insert into localidad (nombre, id_dep) select 'ALONSO', d.id_dep from departamento d where d.nombre = 'PAYSANDU';
insert into localidad (nombre, id_dep) select 'SAN FELIX', d.id_dep from departamento d where d.nombre = 'PAYSANDU';
insert into localidad (nombre, id_dep) select 'VILLA MARIA', d.id_dep from departamento d where d.nombre = 'PAYSANDU';
insert into localidad (nombre, id_dep) select 'BEISSO', d.id_dep from departamento d where d.nombre = 'PAYSANDU';
insert into localidad (nombre, id_dep) select 'T. GUAVIYU', d.id_dep from departamento d where d.nombre = 'PAYSANDU';
insert into localidad (nombre, id_dep) select 'T. ALMIRON', d.id_dep from departamento d where d.nombre = 'PAYSANDU';
insert into localidad (nombre, id_dep) select 'Sin Localidad', d.id_dep from departamento d where d.nombre = 'PAYSANDU';

-- RIO NEGRO
insert into localidad (nombre, id_dep) select 'FRAY BENTOS', d.id_dep from departamento d where d.nombre = 'RIO NEGRO';
insert into localidad (nombre, id_dep) select 'ALGORTA', d.id_dep from departamento d where d.nombre = 'RIO NEGRO';
insert into localidad (nombre, id_dep) select 'BELLACO', d.id_dep from departamento d where d.nombre = 'RIO NEGRO';
insert into localidad (nombre, id_dep) select 'GRAL BORGES', d.id_dep from departamento d where d.nombre = 'RIO NEGRO';
insert into localidad (nombre, id_dep) select 'GRECCO', d.id_dep from departamento d where d.nombre = 'RIO NEGRO';
insert into localidad (nombre, id_dep) select 'LOS ARRAYANES', d.id_dep from departamento d where d.nombre = 'RIO NEGRO';
insert into localidad (nombre, id_dep) select 'LAS CAÑAS', d.id_dep from departamento d where d.nombre = 'RIO NEGRO';
insert into localidad (nombre, id_dep) select 'NUEVO BERLIN', d.id_dep from departamento d where d.nombre = 'RIO NEGRO';
insert into localidad (nombre, id_dep) select 'PASO MELLIZOS', d.id_dep from departamento d where d.nombre = 'RIO NEGRO';
insert into localidad (nombre, id_dep) select 'SARANDI', d.id_dep from departamento d where d.nombre = 'RIO NEGRO';
insert into localidad (nombre, id_dep) select 'SAN JAVIER', d.id_dep from departamento d where d.nombre = 'RIO NEGRO';
insert into localidad (nombre, id_dep) select 'VILLA MARIA', d.id_dep from departamento d where d.nombre = 'RIO NEGRO';
insert into localidad (nombre, id_dep) select 'YOUNG', d.id_dep from departamento d where d.nombre = 'RIO NEGRO';
insert into localidad (nombre, id_dep) select 'Sin Localidad', d.id_dep from departamento d where d.nombre = 'RIO NEGRO';

-- SORIANO
insert into localidad (nombre, id_dep) select 'MERCEDES', d.id_dep from departamento d where d.nombre = 'SORIANO';
insert into localidad (nombre, id_dep) select 'DOLORES', d.id_dep from departamento d where d.nombre = 'SORIANO';
insert into localidad (nombre, id_dep) select 'CARDONA', d.id_dep from departamento d where d.nombre = 'SORIANO';
insert into localidad (nombre, id_dep) select 'JOSE E. RODO', d.id_dep from departamento d where d.nombre = 'SORIANO';
insert into localidad (nombre, id_dep) select 'PALMITAS', d.id_dep from departamento d where d.nombre = 'SORIANO';
insert into localidad (nombre, id_dep) select 'AGRACIADA', d.id_dep from departamento d where d.nombre = 'SORIANO';
insert into localidad (nombre, id_dep) select 'LA CONCORDIA', d.id_dep from departamento d where d.nombre = 'SORIANO';
insert into localidad (nombre, id_dep) select 'PALO SOLO', d.id_dep from departamento d where d.nombre = 'SORIANO';
insert into localidad (nombre, id_dep) select 'RISSO', d.id_dep from departamento d where d.nombre = 'SORIANO';
insert into localidad (nombre, id_dep) select 'EGAÑA', d.id_dep from departamento d where d.nombre = 'SORIANO';
insert into localidad (nombre, id_dep) select 'V. SORIANO', d.id_dep from departamento d where d.nombre = 'SORIANO';
insert into localidad (nombre, id_dep) select 'STA.CATALINA', d.id_dep from departamento d where d.nombre = 'SORIANO';
insert into localidad (nombre, id_dep) select 'CAÑADA NIETO', d.id_dep from departamento d where d.nombre = 'SORIANO';
insert into localidad (nombre, id_dep) select 'LA SIRENA', d.id_dep from departamento d where d.nombre = 'SORIANO';
insert into localidad (nombre, id_dep) select 'Sin Localidad', d.id_dep from departamento d where d.nombre = 'SORIANO';

-- COLONIA
insert into localidad (nombre, id_dep) select 'COLONIA', d.id_dep from departamento d where d.nombre = 'COLONIA';
insert into localidad (nombre, id_dep) select 'RIACHUELO AB', d.id_dep from departamento d where d.nombre = 'COLONIA';
insert into localidad (nombre, id_dep) select 'RIACHUELO AR', d.id_dep from departamento d where d.nombre = 'COLONIA';
insert into localidad (nombre, id_dep) select 'ESTANZUELA', d.id_dep from departamento d where d.nombre = 'COLONIA';
insert into localidad (nombre, id_dep) select 'MIGUELETE', d.id_dep from departamento d where d.nombre = 'COLONIA';
insert into localidad (nombre, id_dep) select 'ROSARIO', d.id_dep from departamento d where d.nombre = 'COLONIA';
insert into localidad (nombre, id_dep) select 'BARKER', d.id_dep from departamento d where d.nombre = 'COLONIA';
insert into localidad (nombre, id_dep) select 'ZANJA HONDA', d.id_dep from departamento d where d.nombre = 'COLONIA';
insert into localidad (nombre, id_dep) select 'BRISAS PLATA', d.id_dep from departamento d where d.nombre = 'COLONIA';
insert into localidad (nombre, id_dep) select 'SANTA REGINA', d.id_dep from departamento d where d.nombre = 'COLONIA';
insert into localidad (nombre, id_dep) select 'LA PAZ', d.id_dep from departamento d where d.nombre = 'COLONIA';
insert into localidad (nombre, id_dep) select 'VALDENSE', d.id_dep from departamento d where d.nombre = 'COLONIA';
insert into localidad (nombre, id_dep) select 'LOS PINOS', d.id_dep from departamento d where d.nombre = 'COLONIA';
insert into localidad (nombre, id_dep) select 'FOMENTO', d.id_dep from departamento d where d.nombre = 'COLONIA';
insert into localidad (nombre, id_dep) select 'PARANT', d.id_dep from departamento d where d.nombre = 'COLONIA';
insert into localidad (nombre, id_dep) select 'PLAYA AZUL', d.id_dep from departamento d where d.nombre = 'COLONIA';
insert into localidad (nombre, id_dep) select 'BRITOPOLIS', d.id_dep from departamento d where d.nombre = 'COLONIA';
insert into localidad (nombre, id_dep) select 'BLANCARENA', d.id_dep from departamento d where d.nombre = 'COLONIA';
insert into localidad (nombre, id_dep) select 'CUFRE', d.id_dep from departamento d where d.nombre = 'COLONIA';
insert into localidad (nombre, id_dep) select 'CARMELO', d.id_dep from departamento d where d.nombre = 'COLONIA';
insert into localidad (nombre, id_dep) select 'ZAGARZAZU', d.id_dep from departamento d where d.nombre = 'COLONIA';
insert into localidad (nombre, id_dep) select 'BAL EL FARO', d.id_dep from departamento d where d.nombre = 'COLONIA';
insert into localidad (nombre, id_dep) select 'PUEBLO GIL', d.id_dep from departamento d where d.nombre = 'COLONIA';
insert into localidad (nombre, id_dep) select 'CONCHILLAS', d.id_dep from departamento d where d.nombre = 'COLONIA';
insert into localidad (nombre, id_dep) select 'R.CONCHILLA', d.id_dep from departamento d where d.nombre = 'COLONIA';
insert into localidad (nombre, id_dep) select 'CAMPANA', d.id_dep from departamento d where d.nombre = 'COLONIA';
insert into localidad (nombre, id_dep) select 'B.DEL OESTE', d.id_dep from departamento d where d.nombre = 'COLONIA';
insert into localidad (nombre, id_dep) select 'NVA PALMIRA', d.id_dep from departamento d where d.nombre = 'COLONIA';
insert into localidad (nombre, id_dep) select 'AGRACIADA', d.id_dep from departamento d where d.nombre = 'COLONIA';
insert into localidad (nombre, id_dep) select 'N. HELVECIA', d.id_dep from departamento d where d.nombre = 'COLONIA';
insert into localidad (nombre, id_dep) select 'O DE LAVALLE', d.id_dep from departamento d where d.nombre = 'COLONIA';
insert into localidad (nombre, id_dep) select 'TARARIRAS', d.id_dep from departamento d where d.nombre = 'COLONIA';
insert into localidad (nombre, id_dep) select 'ANTOLIN', d.id_dep from departamento d where d.nombre = 'COLONIA';
insert into localidad (nombre, id_dep) select 'EL ENSUEÑO', d.id_dep from departamento d where d.nombre = 'COLONIA';
insert into localidad (nombre, id_dep) select 'SANTA ANA', d.id_dep from departamento d where d.nombre = 'COLONIA';
insert into localidad (nombre, id_dep) select 'ARTILLEROS', d.id_dep from departamento d where d.nombre = 'COLONIA';
insert into localidad (nombre, id_dep) select 'F.SANCHEZ', d.id_dep from departamento d where d.nombre = 'COLONIA';
insert into localidad (nombre, id_dep) select 'JUAN LACAZE', d.id_dep from departamento d where d.nombre = 'COLONIA';
insert into localidad (nombre, id_dep) select 'MINUANO', d.id_dep from departamento d where d.nombre = 'COLONIA';
insert into localidad (nombre, id_dep) select 'LA HORQUETA', d.id_dep from departamento d where d.nombre = 'COLONIA';
insert into localidad (nombre, id_dep) select 'CAMPO CHICO', d.id_dep from departamento d where d.nombre = 'COLONIA';
insert into localidad (nombre, id_dep) select 'CARMELO GOLF', d.id_dep from departamento d where d.nombre = 'COLONIA';
insert into localidad (nombre, id_dep) select 'Sin Localidad', d.id_dep from departamento d where d.nombre = 'COLONIA';

-- SAN JOSE
insert into localidad (nombre, id_dep) select 'SAN JOSE U', d.id_dep from departamento d where d.nombre = 'SAN JOSE';
insert into localidad (nombre, id_dep) select 'SAN JOSE S', d.id_dep from departamento d where d.nombre = 'SAN JOSE';
insert into localidad (nombre, id_dep) select 'RODRIGUEZ U', d.id_dep from departamento d where d.nombre = 'SAN JOSE';
insert into localidad (nombre, id_dep) select 'RODRIGUEZ S', d.id_dep from departamento d where d.nombre = 'SAN JOSE';
insert into localidad (nombre, id_dep) select 'ITUZAINGO S', d.id_dep from departamento d where d.nombre = 'SAN JOSE';
insert into localidad (nombre, id_dep) select 'PUEBLO NUEVO S', d.id_dep from departamento d where d.nombre = 'SAN JOSE';
insert into localidad (nombre, id_dep) select '18 DE JULIO S', d.id_dep from departamento d where d.nombre = 'SAN JOSE';
insert into localidad (nombre, id_dep) select 'CAPURRO S', d.id_dep from departamento d where d.nombre = 'SAN JOSE';
insert into localidad (nombre, id_dep) select 'RAIGON S', d.id_dep from departamento d where d.nombre = 'SAN JOSE';
insert into localidad (nombre, id_dep) select 'TROPEZON S', d.id_dep from departamento d where d.nombre = 'SAN JOSE';
insert into localidad (nombre, id_dep) select 'CONCORDIA S', d.id_dep from departamento d where d.nombre = 'SAN JOSE';
insert into localidad (nombre, id_dep) select 'P. DE VARELA S', d.id_dep from departamento d where d.nombre = 'SAN JOSE';
insert into localidad (nombre, id_dep) select 'CHAMIZO', d.id_dep from departamento d where d.nombre = 'SAN JOSE';
insert into localidad (nombre, id_dep) select 'CARR. QUEMADA', d.id_dep from departamento d where d.nombre = 'SAN JOSE';
insert into localidad (nombre, id_dep) select 'SAN GREGORIO', d.id_dep from departamento d where d.nombre = 'SAN JOSE';
insert into localidad (nombre, id_dep) select 'E. PAULLIER U', d.id_dep from departamento d where d.nombre = 'SAN JOSE';
insert into localidad (nombre, id_dep) select 'E. PAULLIER S', d.id_dep from departamento d where d.nombre = 'SAN JOSE';
insert into localidad (nombre, id_dep) select 'LA BOYADA S', d.id_dep from departamento d where d.nombre = 'SAN JOSE';
insert into localidad (nombre, id_dep) select 'BO. SCAVINO S', d.id_dep from departamento d where d.nombre = 'SAN JOSE';
insert into localidad (nombre, id_dep) select 'C.DE PEREYRA', d.id_dep from departamento d where d.nombre = 'SAN JOSE';
insert into localidad (nombre, id_dep) select 'B. DE CUFRE S', d.id_dep from departamento d where d.nombre = 'SAN JOSE';
insert into localidad (nombre, id_dep) select 'LIBERTAD U', d.id_dep from departamento d where d.nombre = 'SAN JOSE';
insert into localidad (nombre, id_dep) select 'LIBERTAD S', d.id_dep from departamento d where d.nombre = 'SAN JOSE';
insert into localidad (nombre, id_dep) select 'P. DE VALDEZ S', d.id_dep from departamento d where d.nombre = 'SAN JOSE';
insert into localidad (nombre, id_dep) select 'R. PERAZA S', d.id_dep from departamento d where d.nombre = 'SAN JOSE';
insert into localidad (nombre, id_dep) select 'VILLA MARIA S', d.id_dep from departamento d where d.nombre = 'SAN JOSE';
insert into localidad (nombre, id_dep) select 'KIL.62 R.1 S', d.id_dep from departamento d where d.nombre = 'SAN JOSE';
insert into localidad (nombre, id_dep) select 'KIL.56 R.1 S', d.id_dep from departamento d where d.nombre = 'SAN JOSE';
insert into localidad (nombre, id_dep) select 'KIL.75 R.3 S', d.id_dep from departamento d where d.nombre = 'SAN JOSE';
insert into localidad (nombre, id_dep) select 'K.62 1/2 R.1 S', d.id_dep from departamento d where d.nombre = 'SAN JOSE';
insert into localidad (nombre, id_dep) select 'R. DEL PINO S', d.id_dep from departamento d where d.nombre = 'SAN JOSE';
insert into localidad (nombre, id_dep) select 'BALN. ORDEIG S', d.id_dep from departamento d where d.nombre = 'SAN JOSE';
insert into localidad (nombre, id_dep) select 'BALN. KIYU S', d.id_dep from departamento d where d.nombre = 'SAN JOSE';
insert into localidad (nombre, id_dep) select 'I. FRANCES S', d.id_dep from departamento d where d.nombre = 'SAN JOSE';
insert into localidad (nombre, id_dep) select 'VISTA MAR S', d.id_dep from departamento d where d.nombre = 'SAN JOSE';
insert into localidad (nombre, id_dep) select 'K.67 R.1 RAD.S', d.id_dep from departamento d where d.nombre = 'SAN JOSE';
insert into localidad (nombre, id_dep) select 'KIL.60 R.1 S', d.id_dep from departamento d where d.nombre = 'SAN JOSE';
insert into localidad (nombre, id_dep) select 'K.67 R.1 DIAZ', d.id_dep from departamento d where d.nombre = 'SAN JOSE';
insert into localidad (nombre, id_dep) select 'K.76.2 R.1 S', d.id_dep from departamento d where d.nombre = 'SAN JOSE';
insert into localidad (nombre, id_dep) select 'MAL ABRIGO S', d.id_dep from departamento d where d.nombre = 'SAN JOSE';
insert into localidad (nombre, id_dep) select 'GONZALEZ S', d.id_dep from departamento d where d.nombre = 'SAN JOSE';
insert into localidad (nombre, id_dep) select 'JUAN SOLER S', d.id_dep from departamento d where d.nombre = 'SAN JOSE';
insert into localidad (nombre, id_dep) select 'LAUREL S', d.id_dep from departamento d where d.nombre = 'SAN JOSE';
insert into localidad (nombre, id_dep) select 'K.77 R.3 SANC.', d.id_dep from departamento d where d.nombre = 'SAN JOSE';
insert into localidad (nombre, id_dep) select 'K.77 R.3 MAR.', d.id_dep from departamento d where d.nombre = 'SAN JOSE';
insert into localidad (nombre, id_dep) select 'K.77 1/2 R.3', d.id_dep from departamento d where d.nombre = 'SAN JOSE';
insert into localidad (nombre, id_dep) select 'KIL.78 R.3 S', d.id_dep from departamento d where d.nombre = 'SAN JOSE';
insert into localidad (nombre, id_dep) select 'D. EL TIGRE S', d.id_dep from departamento d where d.nombre = 'SAN JOSE';
insert into localidad (nombre, id_dep) select 'S. FERNANDO S', d.id_dep from departamento d where d.nombre = 'SAN JOSE';
insert into localidad (nombre, id_dep) select 'P. POSTEL S', d.id_dep from departamento d where d.nombre = 'SAN JOSE';
insert into localidad (nombre, id_dep) select 'SAFICI S', d.id_dep from departamento d where d.nombre = 'SAN JOSE';
insert into localidad (nombre, id_dep) select 'SANTA MONICA S', d.id_dep from departamento d where d.nombre = 'SAN JOSE';
insert into localidad (nombre, id_dep) select 'S. VICTORIA S', d.id_dep from departamento d where d.nombre = 'SAN JOSE';
insert into localidad (nombre, id_dep) select 'K.29 Y 30 R.1', d.id_dep from departamento d where d.nombre = 'SAN JOSE';
insert into localidad (nombre, id_dep) select 'K.30 R.1 MASC.', d.id_dep from departamento d where d.nombre = 'SAN JOSE';
insert into localidad (nombre, id_dep) select 'KIL.34 R.1 GUE', d.id_dep from departamento d where d.nombre = 'SAN JOSE';
insert into localidad (nombre, id_dep) select 'P. PASCUAL S', d.id_dep from departamento d where d.nombre = 'SAN JOSE';
insert into localidad (nombre, id_dep) select 'A. NACIONAL S', d.id_dep from departamento d where d.nombre = 'SAN JOSE';
insert into localidad (nombre, id_dep) select 'P. PENINO S', d.id_dep from departamento d where d.nombre = 'SAN JOSE';
insert into localidad (nombre, id_dep) select 'K.30 R.1 MART.', d.id_dep from departamento d where d.nombre = 'SAN JOSE';
insert into localidad (nombre, id_dep) select 'MONTE GRANDE S', d.id_dep from departamento d where d.nombre = 'SAN JOSE';
insert into localidad (nombre, id_dep) select 'K.30 R.1 GABR.', d.id_dep from departamento d where d.nombre = 'SAN JOSE';
insert into localidad (nombre, id_dep) select 'K.31 R.1 BAO', d.id_dep from departamento d where d.nombre = 'SAN JOSE';
insert into localidad (nombre, id_dep) select 'K.33.8 R.1 ALB', d.id_dep from departamento d where d.nombre = 'SAN JOSE';
insert into localidad (nombre, id_dep) select 'K.32.8 R.1 RAZ', d.id_dep from departamento d where d.nombre = 'SAN JOSE';
insert into localidad (nombre, id_dep) select 'CER.DEL SUR S', d.id_dep from departamento d where d.nombre = 'SAN JOSE';
insert into localidad (nombre, id_dep) select 'Sin Localidad', d.id_dep from departamento d where d.nombre = 'SAN JOSE';

-- FLORES
insert into localidad (nombre, id_dep) select 'TRINIDAD', d.id_dep from departamento d where d.nombre = 'FLORES';
insert into localidad (nombre, id_dep) select 'I.CORTINAS', d.id_dep from departamento d where d.nombre = 'FLORES';
insert into localidad (nombre, id_dep) select 'ANDRESITO', d.id_dep from departamento d where d.nombre = 'FLORES';
insert into localidad (nombre, id_dep) select 'ANDRESITO VIEJO', d.id_dep from departamento d where d.nombre = 'FLORES';
insert into localidad (nombre, id_dep) select 'CERRO COLORADO', d.id_dep from departamento d where d.nombre = 'FLORES';
insert into localidad (nombre, id_dep) select 'JUAN J. CASTRO', d.id_dep from departamento d where d.nombre = 'FLORES';
insert into localidad (nombre, id_dep) select 'Sin Localidad', d.id_dep from departamento d where d.nombre = 'FLORES';

-- FLORIDA
insert into localidad (nombre, id_dep) select 'FLORIDA', d.id_dep from departamento d where d.nombre = 'FLORIDA';
insert into localidad (nombre, id_dep) select 'CASUPA', d.id_dep from departamento d where d.nombre = 'FLORIDA';
insert into localidad (nombre, id_dep) select 'FRAY MARCOS', d.id_dep from departamento d where d.nombre = 'FLORIDA';
insert into localidad (nombre, id_dep) select 'CHAMIZO', d.id_dep from departamento d where d.nombre = 'FLORIDA';
insert into localidad (nombre, id_dep) select 'REBOLEDO', d.id_dep from departamento d where d.nombre = 'FLORIDA';
insert into localidad (nombre, id_dep) select 'LA CRUZ', d.id_dep from departamento d where d.nombre = 'FLORIDA';
insert into localidad (nombre, id_dep) select 'PINTADO', d.id_dep from departamento d where d.nombre = 'FLORIDA';
insert into localidad (nombre, id_dep) select 'NICO PEREZ', d.id_dep from departamento d where d.nombre = 'FLORIDA';
insert into localidad (nombre, id_dep) select 'VALENTINES', d.id_dep from departamento d where d.nombre = 'FLORIDA';
insert into localidad (nombre, id_dep) select 'MENDOZA GRANDE', d.id_dep from departamento d where d.nombre = 'FLORIDA';
insert into localidad (nombre, id_dep) select 'MENDOZA CHICO', d.id_dep from departamento d where d.nombre = 'FLORIDA';
insert into localidad (nombre, id_dep) select 'MANSAVILLAGRA', d.id_dep from departamento d where d.nombre = 'FLORIDA';
insert into localidad (nombre, id_dep) select 'CAP.SAUCE', d.id_dep from departamento d where d.nombre = 'FLORIDA';
insert into localidad (nombre, id_dep) select 'POLANCO YI', d.id_dep from departamento d where d.nombre = 'FLORIDA';
insert into localidad (nombre, id_dep) select 'CERRO CHATO', d.id_dep from departamento d where d.nombre = 'FLORIDA';
insert into localidad (nombre, id_dep) select 'A.GALLINAL', d.id_dep from departamento d where d.nombre = 'FLORIDA';
insert into localidad (nombre, id_dep) select 'SARANDI GDE', d.id_dep from departamento d where d.nombre = 'FLORIDA';
insert into localidad (nombre, id_dep) select 'SARANDI GDE', d.id_dep from departamento d where d.nombre = 'FLORIDA';
insert into localidad (nombre, id_dep) select 'GOÑI', d.id_dep from departamento d where d.nombre = 'FLORIDA';
insert into localidad (nombre, id_dep) select 'PUNTAS MACIEL', d.id_dep from departamento d where d.nombre = 'FLORIDA';
insert into localidad (nombre, id_dep) select '25 DE MAYO', d.id_dep from departamento d where d.nombre = 'FLORIDA';
insert into localidad (nombre, id_dep) select '25-Ago', d.id_dep from departamento d where d.nombre = 'FLORIDA';
insert into localidad (nombre, id_dep) select 'CARDAL', d.id_dep from departamento d where d.nombre = 'FLORIDA';
insert into localidad (nombre, id_dep) select 'INDEPENDENCIA', d.id_dep from departamento d where d.nombre = 'FLORIDA';
insert into localidad (nombre, id_dep) select 'ILLESCAS', d.id_dep from departamento d where d.nombre = 'FLORIDA';
insert into localidad (nombre, id_dep) select 'Sin Localidad', d.id_dep from departamento d where d.nombre = 'FLORIDA';

-- LAVALLEJA
insert into localidad (nombre, id_dep) select 'MINAS', d.id_dep from departamento d where d.nombre = 'LAVALLEJA';
insert into localidad (nombre, id_dep) select 'MARCO D.REYES', d.id_dep from departamento d where d.nombre = 'LAVALLEJA';
insert into localidad (nombre, id_dep) select 'S.FCO.SIERRAS', d.id_dep from departamento d where d.nombre = 'LAVALLEJA';
insert into localidad (nombre, id_dep) select 'SOLIS', d.id_dep from departamento d where d.nombre = 'LAVALLEJA';
insert into localidad (nombre, id_dep) select 'BLLE.ORDOÑEZ', d.id_dep from departamento d where d.nombre = 'LAVALLEJA';
insert into localidad (nombre, id_dep) select 'ILLESCAS', d.id_dep from departamento d where d.nombre = 'LAVALLEJA';
insert into localidad (nombre, id_dep) select 'PIRARAJA', d.id_dep from departamento d where d.nombre = 'LAVALLEJA';
insert into localidad (nombre, id_dep) select 'VILLA SERRANA', d.id_dep from departamento d where d.nombre = 'LAVALLEJA';
insert into localidad (nombre, id_dep) select 'MARISCALA', d.id_dep from departamento d where d.nombre = 'LAVALLEJA';
insert into localidad (nombre, id_dep) select 'COLON', d.id_dep from departamento d where d.nombre = 'LAVALLEJA';
insert into localidad (nombre, id_dep) select 'J.P.VARELA', d.id_dep from departamento d where d.nombre = 'LAVALLEJA';
insert into localidad (nombre, id_dep) select 'ZAPICAN', d.id_dep from departamento d where d.nombre = 'LAVALLEJA';
insert into localidad (nombre, id_dep) select 'ESTACION SOLIS', d.id_dep from departamento d where d.nombre = 'LAVALLEJA';
insert into localidad (nombre, id_dep) select 'SOLIS  SUB', d.id_dep from departamento d where d.nombre = 'LAVALLEJA';
insert into localidad (nombre, id_dep) select 'COLON', d.id_dep from departamento d where d.nombre = 'LAVALLEJA';
insert into localidad (nombre, id_dep) select 'MARISCALA  SUB', d.id_dep from departamento d where d.nombre = 'LAVALLEJA';
insert into localidad (nombre, id_dep) select 'J.P.VARELA SUB', d.id_dep from departamento d where d.nombre = 'LAVALLEJA';
insert into localidad (nombre, id_dep) select 'Sin Localidad', d.id_dep from departamento d where d.nombre = 'LAVALLEJA';

-- DURAZNO
insert into localidad (nombre, id_dep) select 'DURAZNO', d.id_dep from departamento d where d.nombre = 'DURAZNO';
insert into localidad (nombre, id_dep) select 'SARANDI DEL YI', d.id_dep from departamento d where d.nombre = 'DURAZNO';
insert into localidad (nombre, id_dep) select 'CARMEN', d.id_dep from departamento d where d.nombre = 'DURAZNO';
insert into localidad (nombre, id_dep) select 'LA PALOMA', d.id_dep from departamento d where d.nombre = 'DURAZNO';
insert into localidad (nombre, id_dep) select 'BLANQUILLO', d.id_dep from departamento d where d.nombre = 'DURAZNO';
insert into localidad (nombre, id_dep) select 'ROSSELL Y RIUS', d.id_dep from departamento d where d.nombre = 'DURAZNO';
insert into localidad (nombre, id_dep) select 'C. REYLES', d.id_dep from departamento d where d.nombre = 'DURAZNO';
insert into localidad (nombre, id_dep) select 'CENTENARIO', d.id_dep from departamento d where d.nombre = 'DURAZNO';
insert into localidad (nombre, id_dep) select 'CERRO CHATO', d.id_dep from departamento d where d.nombre = 'DURAZNO';
insert into localidad (nombre, id_dep) select 'SAN JORGE', d.id_dep from departamento d where d.nombre = 'DURAZNO';
insert into localidad (nombre, id_dep) select 'CUCHILLA RAMIR', d.id_dep from departamento d where d.nombre = 'DURAZNO';
insert into localidad (nombre, id_dep) select 'AGUAS BUENAS', d.id_dep from departamento d where d.nombre = 'DURAZNO';
insert into localidad (nombre, id_dep) select 'Sin Localidad', d.id_dep from departamento d where d.nombre = 'DURAZNO';

-- TACUAREMBO
insert into localidad (nombre, id_dep) select 'TACUAREMBO', d.id_dep from departamento d where d.nombre = 'TACUAREMBO';
insert into localidad (nombre, id_dep) select 'P DE LOS TOROS', d.id_dep from departamento d where d.nombre = 'TACUAREMBO';
insert into localidad (nombre, id_dep) select 'S.GREGORIO', d.id_dep from departamento d where d.nombre = 'TACUAREMBO';
insert into localidad (nombre, id_dep) select 'LOS FEOS', d.id_dep from departamento d where d.nombre = 'TACUAREMBO';
insert into localidad (nombre, id_dep) select 'CURTINA', d.id_dep from departamento d where d.nombre = 'TACUAREMBO';
insert into localidad (nombre, id_dep) select 'SAUCE DE BATOV', d.id_dep from departamento d where d.nombre = 'TACUAREMBO';
insert into localidad (nombre, id_dep) select 'CUCH. DEL OMBU', d.id_dep from departamento d where d.nombre = 'TACUAREMBO';
insert into localidad (nombre, id_dep) select 'PERALTA', d.id_dep from departamento d where d.nombre = 'TACUAREMBO';
insert into localidad (nombre, id_dep) select 'ANSINA', d.id_dep from departamento d where d.nombre = 'TACUAREMBO';
insert into localidad (nombre, id_dep) select 'LA HILERA', d.id_dep from departamento d where d.nombre = 'TACUAREMBO';
insert into localidad (nombre, id_dep) select 'TAMBORES', d.id_dep from departamento d where d.nombre = 'TACUAREMBO';
insert into localidad (nombre, id_dep) select 'ACHAR', d.id_dep from departamento d where d.nombre = 'TACUAREMBO';
insert into localidad (nombre, id_dep) select 'CARDOSO', d.id_dep from departamento d where d.nombre = 'TACUAREMBO';
insert into localidad (nombre, id_dep) select 'LAURELES', d.id_dep from departamento d where d.nombre = 'TACUAREMBO';
insert into localidad (nombre, id_dep) select 'PASO D.CERRO', d.id_dep from departamento d where d.nombre = 'TACUAREMBO';
insert into localidad (nombre, id_dep) select 'IPORA', d.id_dep from departamento d where d.nombre = 'TACUAREMBO';
insert into localidad (nombre, id_dep) select 'CARAGUATA', d.id_dep from departamento d where d.nombre = 'TACUAREMBO';
insert into localidad (nombre, id_dep) select 'PIEDRA SOLA', d.id_dep from departamento d where d.nombre = 'TACUAREMBO';
insert into localidad (nombre, id_dep) select 'PASO BONILLA', d.id_dep from departamento d where d.nombre = 'TACUAREMBO';
insert into localidad (nombre, id_dep) select 'Sin Localidad', d.id_dep from departamento d where d.nombre = 'TACUAREMBO';

-- MONTEVIDEO
insert into localidad (nombre, id_dep) select 'MONTEVIDEO', d.id_dep from departamento d where d.nombre = 'MONTEVIDEO';
insert into localidad (nombre, id_dep) select 'Sin Localidad', d.id_dep from departamento d where d.nombre = 'MONTEVIDEO';

